name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  node-version:
    description: 'Node.js version'
    required: true
    default: '14.x'
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  client-id:
    description: 'Client id to login to azure'
    required: true
  tenant-id:
    description: 'Tenant id to login to azure'
    required: true
  subscription-id:
    description: 'Subscription id to be used with your az login'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
#runs:
  # using: 'node20'
  # main: 'dist/index.js'
runs:
  using: 'composite'
  steps:
    - name: 'Checkout repository'
      uses: 'actions/checkout@v2'
    - name: 'Setup Node.js'
      uses: 'actions/setup-node@v2'
      with:
        node-version: $ { { inputs.node-version }}
    - name: 'az cli login'
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: false
    - name: 'Run hello.js'
      run: node dist/index.js
      shell: bash
