name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
#runs:
  # using: 'node20'
  # main: 'dist/index.js'
runs:
  using: 'composite'
  steps:
    - name: 'Checkout repository'
      uses: 'actions/checkout@v2'
    - name: 'Setup Node.js'
      uses: 'actions/setup-node@v2'
      with:
        node-version: $ { { inputs.node-version }}
    - name: 'az cli login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false
    - name: 'Run hello.js'
      run: node dist/index.js
      shell: bash
